cpus: 2                                                 # Number of vCPUs
ram: 8192                                               # RAM size in MBs
disk1_size: 50                                          # Disk size in Gbs
folder: "{{ infra_folder }}"                            # Where the VM template is stored
template: "{{ infra_template }}"                        # Name of the template
ova_path: "{{ infra_ova_path }}"                        # Name of the OVA used to import the template

#
# with cloud init_data:
#
customvalues: 
  - key: guestinfo.metadata
    value: "{{ cloud_init_metadata_data }}"
  - key: guestinfo.metadata.encoding
    value: base64
  - key: guestinfo.userdata
    value:  "{{ cloud_init_users_data }}"
  - key: guestinfo.userdata.encoding
    value: base64
networks:
  - name: '{{ vm_portgroup }}'
  - name: '{{ frontend_vm_portgroup }}'
customization: {}
disks_specs:
  - size_gb:  '{{ disk1_size }}'
    type: thin
    datastore: "{{ datastores | random }}"

cloud_init_networks:
  version: 1
  config:
  - type: physical
    name: ens192
    subnets:
      - type: static
        address: "{{ hostvars[inventory_hostname].ansible_host }}"
        netmask: "{{ dhcp_subnet | ipaddr('netmask') }}"
        gateway: "{{ gateway }}"
        dns_nameservers: "{{ internal_dns_servers | union(dns_servers) }}"
        dns_search:
          - "{{ cluster_name }}.{{ domain_name }}"
  - type: physical
    name: ens224
    subnets:
      - type: static
        address: "{{ hostvars[inventory_hostname].frontend_ipaddr | ipaddr('address') }}"
        netmask: "{{ hostvars[inventory_hostname].frontend_ipaddr | ipaddr('netmask') }}"
#        gateway: "{{ frontend_gateway }}"
