cpus: '4'                                               # Number of vCPUs
ram: '16384'                                            # RAM size in MBs
disk1_size: '120'                                       # Disk size in GBs
folder: "{{ cluster_name }}"                            # Where the VM will be stored
template: "{{ rhcos_worker_template }}"                 # Override the default CoreOS template
ova_path: "{{ rhcos_worker_ova_path }}"                 # Name of the OVA used to import the template
ignition_file: '{{ install_dir }}/worker.ign'           # location of the ignition data
initial_port_check: 22                                  # This is the SSH port
initial_port_check_timeout: 10                          # Seconds waiting for port 22 to be open

customvalues:
  - key: disk.EnableUUID
    value: "TRUE"
  - key: guestinfo.ignition.config.data
    value: "{{ ignition_data }}"
  - key: guestinfo.ignition.config.data.encoding
    value: base64
  - key: sched.cpu.latencySensitivity
    value: High
networks: []
customization: {}
disks_specs:
  - size_gb:  '{{ disk1_size }}'
    type: thin
    datastore: "{{ datastores | random }}"
