cpus: '4'                                               # Number of vCPUs
ram: '16384'                                            # RAM size in MBs
disk1_size: '120'                                       # Disk size in GBs
folder: "{{ cluster_name }}"                            # Where the VM will be stored
template: hpe-rhel760                                   # Override the default template
ova_path: /kits/hpe-rhel760.ova                         # Name of the OVA used to import the template

#
# with cloud-init
#
customvalues: 
  - key: disk.EnableUUID
    value: "TRUE"
  - key: guestinfo.metadata
    value: "{{ cloud_init_metadata_data }}"
  - key: guestinfo.metadata.encoding
    value: base64
  - key: guestinfo.userdata
    value:  "{{ cloud_init_users_data }}"
  - key: guestinfo.userdata.encoding
    value: base64
networks:
  - name: '{{ vm_portgroup }}'
customization: {}
disks_specs:
  - size_gb:  '{{ disk1_size }}'
    type: thin
    datastore: "{{ datastores | random }}"

cloud_init_networks:
  version: 1
  config:
  - type: physical
    name: ens192
    subnets:
      - type: static
        address: "{{ hostvars[inventory_hostname].ansible_host }}"
        netmask: "{{ dhcp_subnet | ipaddr('netmask') }}"
        gateway: "{{ gateway }}"
        dns_nameservers: "{{ internal_dns_servers | union(dns_servers) }}"
        dns_search:
          - "{{ cluster_name }}.{{ domain_name }}"
