---
- import_playbook: playbooks/prepare.yml
- import_playbook: playbooks/provision.yml
- import_playbook: playbooks/configure.yml
- import_playbook: playbooks/poweron.yml
- import_playbook: playbooks/finish.yml
