###
# Copyright (2017) Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
### 
---
- name: Open firewall ports
  become: true
  firewalld:
    port: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  with_items:
  - 111/tcp
  - 111/udp
  - 2049/tcp
  - 2049/udp
  - 892/tcp
  - 892/udp
  - 662/tcp
  - 662/udp
  - 32803/tcp
  - 32769/udp

#
# NFS Share for K8S PVs
#
#- name: Check for partitions on 3rd disk
#  parted:
#    state: info
#    device: /dev/sdc
#    number: 1
#  register: Disk3Info

#- set_fact:
#    partPresent: "{{ Disk3Info.partitions[0] is defined }}"

#- name: Create partition on 3rd disk
#  parted:
#    device: /dev/sdc
#    number: 1
#    state: present
#  when: partPresent == false

#- name: Create filesystem on 3rd disk
#  filesystem:
#    fstype: xfs
#    dev: '/dev/sdc1'
#  when: partPresent == false

- name: Create Share for K8S Persistent Volumes
  become: true
  file:
    path: "{{ nfs_share }}{{ item }}"
    state: directory
    mode: 0777
  with_items:
  - "{{ range (22) | list }}"

#- name: Mount filesystem
#  mount:
#    path: "{{ nfs_provisioner_server_share }}"
#    src: '/dev/sdc1'
#    fstype: xfs
#    state: mounted

- name: Install NFS server
  become: true  
  package:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - rpcbind
    - nfs-utils

- name: Enable and start NFS services on server
  become: true  
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - rpcbind
    - nfs-server
    - nfs-lock
    - nfs-idmap

- name: Modify exports file on NFS server
  become: true  
  template: 
    src: exports.j2
    dest: /etc/exports
  notify: Refresh ExportFS

