#
# Don't change anything in this file unless you know what you are doing
#
#
# Default value
#
ignition_file: /dev/null
#
# Rely on DRS to place VMs, if DRS is not enabled, this variable can be specified in the inventory file for each host
#
esxi_host: ''

#
# api and api_int point to loadbalancer[0] IP if loadbalancers is not defined
#
lb_api_ip:      "{% if loadbalancers.frontend.vip is defined %}{{ loadbalancers.frontend.vip }}{% else %}{{ hostvars[groups.loadbalancer.0].frontend_ipaddr }}{% endif %}"
lb_api_int_ip:  "{% if loadbalancers.backend.vip  is defined %}{{ loadbalancers.backend.vip  }}{% else %}{{ hostvars[groups.loadbalancer.0].ansible_host }}/{{ dhcp_subnet|ipaddr('prefix') }}{% endif %}"
lb_apps_ip:     "{% if loadbalancers.apps.vip     is defined %}{{ loadbalancers.apps.vip     }}{% else %}{{ hostvars[groups.loadbalancer.0].frontend_ipaddr }}{% endif %}"
