---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-operators-redhat
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-logging: "true"
    openshift.io/cluster-monitoring: "true"

---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-operators-redhat
  namespace: openshift-operators-redhat 
spec: {}

#---
#apiVersion: "operators.coreos.com/v1"
#kind: "CatalogSourceConfig"
#metadata:
#  name: "elasticsearch"
#  namespace: "openshift-marketplace"
#spec:
#  targetNamespace: "openshift-operators-redhat" 
#  packages: "elasticsearch-operator"
