###
# Copyright (2017) Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
### 

- name: Verify Presence of Required files
  stat:
    path: "{{ item }}"
  register: res
  failed_when: res.stat.exists == false
  with_items:
    - "{{ ocp_installer_path }}"
    - "{{ ocp_oc_path }}"
    - "{{ ocp_kubectl_path }}"

- name: Install client tools
  become: true
  copy:
    src: "{{ item }}"
    dest: /usr/local/bin/
    mode: u=rwx,g=rx,o=rx
  with_items:
    - "{{ ocp_oc_path }}"
    - "{{ ocp_kubectl_path }}"
  

- name: Create Support Folder
  vcenter_folder:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    datacenter: "{{ datacenter }}"
    folder_name: "{{ support_folder }}"
    folder_type: vm
    state: present

- name: create Cluster Folder
  vcenter_folder:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    datacenter: "{{ datacenter }}"
    folder_name: "{{ cluster_name }}"
    folder_type: vm
    state: present

- name: Populate /etc/hosts
  become: true
  blockinfile:
    path: /etc/hosts
    block: |
      {{ lb_api_int_ip | ipaddr('address') }} api-int api-int.{{ cluster_name }}.{{ domain_name }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK api-int"

- name: Populate /etc/hosts
  become: true
  blockinfile:
    path: /etc/hosts
    block: |
      {{ lb_api_ip | ipaddr('address') }} api api.{{ cluster_name }}.{{ domain_name }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK api"

- name: Populate /etc/hosts
  become: true
  blockinfile:
    path: /etc/hosts
    block: |
      {{ hostvars[item].ansible_host }} {{ hostvars[item].inventory_hostname }}  {{ hostvars[item].inventory_hostname }}.{{ cluster_name }}.{{ domain_name }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ hostvars[item].inventory_hostname }}"
  with_items:
  - "{{ groups['all'] | difference (groups.local) }}"

- name: Install http server on the ansible box
  become: true
  package:
    name: httpd
    state: present

- name: Make sure http is started
  become: true
  systemd:
    name: httpd
    state: started

- name: Configure required firewall ports
  become: true
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: true
    state: enabled
  with_items:
  - 80/tcp
