apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: msad
    mappingMethod: claim 
    type: LDAP
    ldap:
      attributes:
        id: 
        - name
        email: 
        - UserPrincipalName
        name: 
        - cn
        preferredUsername: 
        - sAMAccountName
      bindDN: "{{ ldap_bind_user_dn }}"
      bindPassword: 
        name: ldap-secret
      ca: 
        name: ca-config-map
      insecure: false 
      url: "ldaps://mars-adds.am2.cloudra.local/CN=Users,DC=am2,DC=cloudra,DC=local?sAMAccountName??(objectClass=person)"
