###
# Copyright (2019) Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
### 
---
- name: Configure required firewall ports
  become: true
  firewalld:
    port: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  with_items:
    - 53/tcp
    - 53/udp

- name: Install dnsmasq
  become: true
  package:
    name: dnsmasq
    state: present

- name: Create Resolv.conf file
  become: true
  template:
     src: dnsmasq-resolv.conf.j2
     dest: /var/lib/dnsmasq/resolv.conf
  notify: Restart DNS Services

- name: Add DNS records required by OCP
  become: true
  template:
     src: dnsmasq_etcd.conf.j2
     dest: /etc/dnsmasq.d/k8s.conf
  notify: Restart DNS Services

- name: Populate DNS (dnsmasq)
  become: true
  template:
    src: hosts.j2
    dest: /etc/hosts
  notify: Restart DNS Services
