###
# Copyright (2019) Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
### 
- name: See if VM template already loaded
  run_once: true
  delegate_to: localhost
  vmware_guest_facts:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    datacenter: "{{ datacenter }}"
    folder: "{{ datacenter }}/vm/{{ support_folder }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    name: "{{ template }}"
  failed_when: false
  register: vm_facts

- name: Verify Presence of OVA file if template not found
  run_once: true
  delegate_to: localhost
  stat:
    path: "{{ item }}"
  register: res
  failed_when: res.stat.exists == false
  with_items:
    - "{{ ova_path }}"
  when: vm_facts.instance is not defined

- name: Deploy OVA
  run_once: true
  delegate_to: localhost
  vmware_deploy_ovf:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    ova: "{{ ova_path }}"
    cluster: "{{ vcenter_cluster }}"
    datacenter: "{{ datacenter }}"
    folder: "{{ datacenter }}/vm/{{ support_folder }}"
    datastore: "{{ datastores | random }}"
    disk_provisioning: thin
    networks: '{"VM Network":"{{ vm_portgroup }}"}'
    name: "{{ template }}"
    power_on: no
    allow_duplicates: no
  when: vm_facts.instance is not defined
  register: res

