---
# defaults file for infrastructure
#
# ports 647 and 79111 needed if impleneting ISC DHCP Failover,
#    it seems Failover is not needed when only static leases are configured
#    comment out the code with #### in case we need to re-enable
#

#if implementing failover, but we don't because we only accept known client
#dhcpd_ports:
#- 67/udp
#- 647/tcp
#- 7911/tcp

dhcpd_ports:
- 67/udp
